/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        surface: 'var(--surface)',
        'surface-hover': 'var(--surface-hover)',
        'surface-active': 'var(--surface-active)',
        primary: {
          DEFAULT: '#6366f1',
          hover: '#4f46e5',
          light: '#818cf8',
        },
        accent: {
          purple: '#a855f7',
          pink: '#ec4899',
          cyan: '#06b6d4',
          emerald: '#10b981',
          amber: '#f59e0b',
        },
        charcoal: {
          950: '#07080b',
          900: '#0d0f14',
          850: '#12151c',
          800: '#181c26',
          700: '#232938',
          600: '#343d52',
          500: '#525e7a',
        },
      },
      fontFamily: {
        sans: [
          '-apple-system',
          'BlinkMacSystemFont',
          '"SF Pro Text"',
          '"SF Pro Display"',
          '"Helvetica Neue"',
          'Helvetica',
          '"Noto Sans"',
          'Arial',
          'sans-serif',
        ],
        display: [
          '-apple-system',
          'BlinkMacSystemFont',
          '"SF Pro Display"',
          '"SF Pro Text"',
          '"Helvetica Neue"',
          'Helvetica',
          '"Noto Sans"',
          'Arial',
          'sans-serif',
        ],
        mono: [
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Monaco',
          'Consolas',
          '"Liberation Mono"',
          '"Courier New"',
          'monospace',
        ],
        urdu: ['"Noto Nastaliq Urdu"', '"Noto Sans Arabic"', 'Tahoma', 'sans-serif'],
        arabic: ['"Noto Sans Arabic"', '"Segoe UI Arabic"', 'Tahoma', 'sans-serif'],
        devanagari: ['"Noto Sans Devanagari"', 'Mangal', '"Segoe UI"', 'sans-serif'],
        bengali: ['"Noto Sans Bengali"', 'Vrinda', '"Segoe UI"', 'sans-serif'],
        gurmukhi: ['"Noto Sans Gurmukhi"', 'Raavi', '"Segoe UI"', 'sans-serif'],
        gujarati: ['"Noto Sans Gujarati"', 'Shruti', '"Segoe UI"', 'sans-serif'],
        tamil: ['"Noto Sans Tamil"', 'Latha', '"Segoe UI"', 'sans-serif'],
        telugu: ['"Noto Sans Telugu"', 'Gautami', '"Segoe UI"', 'sans-serif'],
        kannada: ['"Noto Sans Kannada"', 'Tunga', '"Segoe UI"', 'sans-serif'],
        malayalam: ['"Noto Sans Malayalam"', 'Kartika', '"Segoe UI"', 'sans-serif'],
        japanese: ['"Noto Sans JP"', '"Hiragino Sans"', 'Meiryo', 'sans-serif'],
        korean: ['"Noto Sans KR"', '"Malgun Gothic"', '"Apple SD Gothic Neo"', 'sans-serif'],
        cjk: ['"Noto Sans SC"', '"PingFang SC"', '"Microsoft YaHei"', 'sans-serif'],
        thai: ['"Noto Sans Thai"', 'Leelawadee UI', 'sans-serif'],
      },
      fontSize: {
        'large-title': ['34px', { lineHeight: '41px', letterSpacing: '-0.025em', fontWeight: '700' }],
        'title-1': ['28px', { lineHeight: '34px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'title-2': ['22px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'title-3': ['20px', { lineHeight: '25px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline': ['17px', { lineHeight: '22px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body': ['16px', { lineHeight: '22px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'callout': ['15px', { lineHeight: '20px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'subheadline': ['14px', { lineHeight: '19px', letterSpacing: '0em', fontWeight: '400' }],
        'footnote': ['13px', { lineHeight: '18px', letterSpacing: '0.005em', fontWeight: '400' }],
        'caption-1': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '400' }],
        'caption-2': ['11px', { lineHeight: '14px', letterSpacing: '0.015em', fontWeight: '400' }],
      },
      animation: {
        'pulse-subtle': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'spin-slow': 'spin 12s linear infinite',
        'shimmer': 'shimmer 2s linear infinite',
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
      boxShadow: {
        'glow-sm': '0 2px 12px -2px rgba(255, 255, 255, 0.08)',
        'glow-md': '0 4px 20px -4px rgba(255, 255, 255, 0.12)',
        'glow-lg': '0 8px 32px -6px rgba(255, 255, 255, 0.15)',
        'surface-elevated': '0 12px 48px -12px rgba(0, 0, 0, 0.7), 0 4px 16px -4px rgba(0, 0, 0, 0.5)',
        'play-btn': '0 2px 8px rgba(0, 0, 0, 0.3), 0 6px 20px -4px rgba(0, 0, 0, 0.25)',
        'dock': '0 20px 50px -10px rgba(0, 0, 0, 0.7), 0 0 0 1px rgba(255, 255, 255, 0.08)',
        'floating': '0 16px 40px -10px rgba(0, 0, 0, 0.6), 0 0 0 1px rgba(255, 255, 255, 0.07)',
        'artwork': '0 8px 30px -4px rgba(0, 0, 0, 0.5), 0 20px 60px -12px rgba(0, 0, 0, 0.4)',
        'artwork-lg': '0 12px 40px -4px rgba(0, 0, 0, 0.6), 0 28px 80px -16px rgba(0, 0, 0, 0.5)',
      },
      transitionTimingFunction: {
        'out-expo': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'spring': 'cubic-bezier(0.2, 0, 0, 1)',
      },
    },
  },
  plugins: [],
}
